* TOP500 list web scraping

This is a project to do web scraping of the [[https://www.top500.org/][TOP500 list]], which is a list of the
500 most powerful commercially available computers in the world.

The goal of this project is to extract the details of the computers from the
lists presented in the web site as HTML tables and store them in CSV format for
later processing.
** The www.top500.org web site structure

The lists are created twice a year (in June and November each year), and the web
site presents each edition of the list split across 5 pages, with 100 entries
each.

Each page has one table with one row per entry. Each row provides these details
about each supercomputer:

  - *Rank*: the order of the supercomputer in that edition of the list
  - *Site*: where is the supercomputer located
  - *System*: name of the system
  - *Cores*: number of compute cores
  - *Rmax*: maximal LINPACK performance achieved (TFlop/s)
  - *Rpeak*: theoretical peak performance (TFlop/s)
  - *Power*: power consumption (kW)

Details of the collected information are available on their [[https://www.top500.org/project/top500_description/][description page]].

** robots.txt

#+BEGIN_EXAMPLE
$ curl https://www.top500.org/robots.txt
User-agent: *
Allow: /

Host: www.top500.org
#+END_EXAMPLE

** Dependencies

  - Python 3
  - [[http://docs.python-requests.org/][Python Requests]]. The ~requests~ Python module is used to download the pages.
  - [[https://www.crummy.com/software/BeautifulSoup/bs4/doc/][Beatuful Soup]]. Python ~BeautifulSoup~ is used to parse the pages.

* Notes

Some notes about the website structure, to keep in mind during scraping.

** List page

*** Number format
Numbers are written in US format, with commas to separate thousands and dots for
the decimal point.

Conversion is performed using the ~locale~ module, setting locale to
~en_US.UTF-8~ and using the ~atoi~ and ~atof~ functions.

*** Highlights list vs full list

Each edition of the list has a /highlights/ list with the top 10 for that
edition. That list has 6 columns, where the 2nd column contains both the system
and the site mixed in.

The tables with the full list contain 7 columns: the 2nd column contains the
site and the 3rd contains the system.

We scrape only the full lists, as the highlights/summary do not provide any
additional information.

*** List structure: sites and systems

A system (3rd column in the list) looks like this in most cases:

#+BEGIN_EXAMPLE
  <td><a href="https://www.top500.org/system/SYSTEM_ID">
      SYSTEM_NAME, PROCESSOR, INTERCONNECT, COPROCESSORS
  </a><br/>MANUFACTURER</td>
#+END_EXAMPLE

However:

 - not all systems provide information about the processors and/or interconnect
   in the listing page. For example, [[https://www.top500.org/system/176928][Tera-100 - Bull bullx super-node
   S6010/S6030]].

 - some systems also include GPU information, like [[https://www.top500.org/system/178467][QB-2 - Dell C8220X Cluster,
   Intel Xeon E5-2680v2 10C 2.8GHz, Infiniband FDR, NVIDIA K20x]]. GPU information
   is not detailed in the system details page.

 - some systems have more than one type of coprocessor, e.g. [[https://www.top500.org/system/178524][Thunder - SGI ICE
   X, Xeon E5-2699v3/E5-2697 v3, Infiniband FDR, NVIDIA Tesla K40, Intel Xeon
   Phi 7120P]]. We bundle all of them together in the /gpu/ field.

 - some systems include GPU information at the beginning of their name,
   e.g. [[https://www.top500.org/system/177996][SANAM - Adtech, ASUS ESC4000/FDR G2, Xeon E5-2650 8C 2.000GHz, Infiniband
   FDR, AMD FirePro S10000]].

 - some systems have the order of the fields reversed, like [[https://www.top500.org/system/179200][Inspur SA5212H5,
   Xeon E5-2682v4 16C 2.5GHz, NVIDIA Tesla P100, 25G Ethernet]] which lists the
   interconnect after the GPU.

A site (2nd column in the list) looks like this:

#+BEGIN_EXAMPLE
  <td><a href="https://www.top500.org/site/SITE_ID">SITE_NAME</a><br>COUNTRY</td>
#+END_EXAMPLE

** System details page

*** Power
Several /Power/ values are marked as "(Submitted)", e.g. https://www.top500.org/system/177981.

Some have "(Derived)": https://www.top500.org/system/178751

Many have no value in this field.

*** Some systems evolve over time

Several fields can change, including the system's name, number of cores, Rmax, Rpeak, Power, ...

Examples:
 - https://www.top500.org/system/178192
 - https://www.top500.org/system/177459
 - https://www.top500.org/system/177449

